version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: p2_db_mysql_despachos
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-p2_db}
      MYSQL_USER: ${DB_USER:-admin_p2}
      MYSQL_PASSWORD: ${DB_PASSWORD:-super_secret_password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-super_secret_root_password}
    ports:
      - "3306:3306" # En la EC2 dedicada podemos usar el puerto nativo 3306
    volumes:
      - db_data_despachos:/var/lib/mysql
    networks:
      - despachos_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER:-admin_p2}", "-p${DB_PASSWORD:-super_secret_password}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-despachos:
    image: ${DOCKER_USERNAME}/backend-despachos:latest
    container_name: p2_backend_despachos
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME:-p2_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-admin_p2}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-super_secret_password}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - despachos_network

networks:
  despachos_network:
    driver: bridge

volumes:
  db_data_despachos:
    driver: local