services:
  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops/backend-despachos:${IMAGE_TAG:-latest}
    container_name: app-despachos
    restart: always
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops/backend-ventas:${IMAGE_TAG:-latest}
    container_name: app-ventas
    restart: always
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge