version: '3.8'

services:
  backend-ventas:
    image: ${DOCKER_USERNAME}/backend-ventas:latest
    container_name: app-ventas
    restart: always
    ports:
      - "8082:8082"
    environment:
      # variable DB_HOST_IP  por el pipeline con la IP Privada de la EC2 de Despachos
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST_IP}:3306/${DB_NAME:-proyecto_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-admin}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-admin123}
      - SERVER_PORT=8082
      - DB_ENDPOINT=${DB_HOST_IP}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-proyecto_db}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
    networks:
      - ventas-network

networks:
  ventas-network:
    driver: bridge