apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: 058264296562.dkr.ecr.us-east-1.amazonaws.com/mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom: { secretKeyRef: { name: db-secrets, key: DB_NAME } }
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: db-secrets, key: DB_PASSWORD } }
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP