name: CI/CD Backend Monorepo ECS Fargate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECS_CLUSTER: cluster-examen-final

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test - Ventas
      working-directory: back-Ventas_SpringBoot/Springboot-API-REST
      # Se rectifica el comando para asegurar la construcción del .jar
      run: mvn -B clean package

    - name: Build and Test - Despachos
      working-directory: back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      run: mvn -B clean package

    # Se desacoplan los procesos de construcción en pasos atómicos
    - name: Build and Push Image - Ventas
      id: build-push-ventas
      working-directory: back-Ventas_SpringBoot/Springboot-API-REST
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/devops/backend-ventas:$IMAGE_TAG -t $ECR_REGISTRY/devops/backend-ventas:latest .
        docker push $ECR_REGISTRY/devops/backend-ventas:$IMAGE_TAG
        docker push $ECR_REGISTRY/devops/backend-ventas:latest
        echo "VENTAS_IMAGE=$ECR_REGISTRY/devops/backend-ventas:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build and Push Image - Despachos
      id: build-push-despachos
      working-directory: back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/devops/backend-despachos:$IMAGE_TAG -t $ECR_REGISTRY/devops/backend-despachos:latest .
        docker push $ECR_REGISTRY/devops/backend-despachos:$IMAGE_TAG
        docker push $ECR_REGISTRY/devops/backend-despachos:latest
        echo "DESPACHOS_IMAGE=$ECR_REGISTRY/devops/backend-despachos:$IMAGE_TAG" >> $GITHUB_ENV
      

    # --- DESPLIEGUE VENTAS ---
    - name: Fill in the new image ID in the Amazon ECS task definition for Ventas
      id: task-def-ventas
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/task-def-ventas.json
        container-name: contenedor-ventas
        image: ${{ env.VENTAS_IMAGE }}

    - name: Deploy Amazon ECS task definition for Ventas
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def-ventas.outputs.task-definition }}
        service: servicio-ventas
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    # --- DESPLIEGUE DESPACHOS ---
    - name: Fill in the new image ID in the Amazon ECS task definition for Despachos
      id: task-def-despachos
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/task-def-despachos.json
        container-name: contenedor-despachos
        image: ${{ env.DESPACHOS_IMAGE }}

    - name: Deploy Amazon ECS task definition for Despachos
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def-despachos.outputs.task-definition }}
        service: servicio-despachos
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true