name: CI/CD Backend Monorepo EKS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: serious-synth-outfit
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Images
      id: build-push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Ventas
        cd back-Ventas_SpringBoot/Springboot-API-REST
        docker build -t $ECR_REGISTRY/backend-ventas:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/backend-ventas:latest .
        docker push $ECR_REGISTRY/backend-ventas:$IMAGE_TAG
        docker push $ECR_REGISTRY/backend-ventas:latest

        # Despachos
        cd ${{ github.workspace }}/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker build -t $ECR_REGISTRY/backend-despachos:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/backend-despachos:latest .
        docker push $ECR_REGISTRY/backend-despachos:$IMAGE_TAG
        docker push $ECR_REGISTRY/backend-despachos:latest

        # Exportar variables para el siguiente paso
        echo "REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV

    - name: Configure Kubectl & Deploy
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
        
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/database.yaml
        kubectl apply -f k8s/api-ventas.yaml
        kubectl apply -f k8s/api-despachos.yaml

        # Usamos las variables exportadas
        kubectl set image deployment/api-ventas-deploy ventas=${{ env.REGISTRY }}/backend-ventas:$IMAGE_TAG
        kubectl set image deployment/api-despachos-deploy despachos=${{ env.REGISTRY }}/backend-despachos:$IMAGE_TAG
        
        # Reiniciar solo los servicios cambiados, no la base de datos
        kubectl rollout restart deployment api-ventas-deploy
        kubectl rollout restart deployment api-despachos-deploy